<template>
  <section class="page-section">

    <section
      v-for="(block, index) in section"
      :id="block.id"
      :key="index"
      class="content-section">
      <div :class="`grid${block.grid && block.grid.middle ? '-middle' : ''}`">

        <template v-if="block.type !== 'custom'">
          <!-- ////////////////////////////////////////////////// [col] left -->
          <div
            v-if="block.hasOwnProperty('left')"
            :class="block.left.cols.num"
            :data-push-left="block.left.cols.hasOwnProperty('push_left') ? block.left.cols.push_left : undefined"
            :data-push-right="block.left.cols.hasOwnProperty('push_right') ? block.left.cols.push_right : undefined">
            <div class="column-content left">

              <!-- =================================  [blocks] autogenerated -->
              <div class="blocks left">
                <TextBlock
                  v-if="block.left.type === 'text_block'"
                  :block="block.left" />
                <ImageBlock
                  v-if="block.left.type === 'image_block'"
                  :block="block.left" />
                <VideoBlock
                  v-if="block.left.type === 'video_block'"
                  :block="block.left" />
                <SliderBlock
                  v-if="block.left.type === 'slider_block'"
                  :block="block.left" />
              </div>

              <!-- ===============================================  [custom] -->
              <BackgroundLayers
                v-if="block.id === 'banner_1'"
                :layers-array="[8, 6, 5, 4, 2, 1]"
                :offset="1.375" />

            </div>
          </div>

          <!-- ///////////////////////////////////////////////// [col] right -->
          <div
            v-if="block.hasOwnProperty('right')"
            :class="block.right.cols.num"
            :data-push-left="block.right.cols.hasOwnProperty('push_left') ? block.right.cols.push_left : undefined"
            :data-push-right="block.right.cols.hasOwnProperty('push_right') ? block.right.cols.push_right : undefined">
            <div class="column-content right">

              <!-- =================================  [blocks] autogenerated -->
              <div class="blocks right">
                <TextBlock
                  v-if="block.right.type === 'text_block'"
                  :block="block.right" />
                <ImageBlock
                  v-if="block.right.type === 'image_block'"
                  :block="block.right" />
                <VideoBlock
                  v-if="block.right.type === 'video_block'"
                  :block="block.right" />
                <SliderBlock
                  v-if="block.right.type === 'slider_block'"
                  :block="block.right" />
              </div>

              <!-- ===============================================  [custom] -->
              <BackgroundLayers
                v-if="block.id === 'intro_1'"
                :layers-array="[8, 6, 5, 4, 2, 1]"
                :offset="1.375" />

              <BackgroundLayers
                v-if="block.id === 'get_involved'"
                :layers-array="[8, 6, 5, 4]"
                :border-radius="5"
                :offset="1.375" />

            </div>
          </div>
        </template>

      </div>
    </section>

  </section>
</template>

<script>
// ====================================================================== Import
import TextBlock from '@/components/TextBlock'
import ImageBlock from '@/components/ImageBlock'
import VideoBlock from '@/components/VideoBlock'
import SliderBlock from '@/components/SliderBlock'
import BackgroundLayers from '@/components/BackgroundLayers'

// ====================================================================== Export
export default {
  name: 'PageSection',

  components: {
    TextBlock,
    ImageBlock,
    VideoBlock,
    SliderBlock,
    BackgroundLayers
  },

  props: {
    section: {
      type: Array,
      required: true
    }
  }
}
</script>

<style lang="scss" scoped>
// ///////////////////////////////////////////////////////////////////// General
.page-section {
  position: relative;
  z-index: 5;
}

.content-section {
  padding: 5rem 0;
}

.column-content {
  position: relative;
}

.blocks {
  position: relative;
  z-index: 10;
}
</style>
