---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Site Data
- type: heading
  label: Content
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post-front-matter
- type: directory
  path: content/pages
  label: Pages
  create: documents
  match: "**/*"
  new_doc_ext: json
  templates:
  - page-index
  - page-grants
  - page-terms
  - page-policy
  - page-governance
  - page-about
  - page-ecosystem
  - page-blog
  - page-events
  - page-basic-template-1
  - page-basic-template-2
  - page-get-involved
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
