---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Site Data
- type: document
  path: content/pages/general.json
  label: General
- type: heading
  label: Content
- type: directory
  path: content/pages
  label: Pages
  create: documents
  match: "**/*"
  exclude: general.json
  new_doc_ext: json
  templates:
  - page-fil-austin
  - page-index
  - page-grants
  - page-policy
  - page-governance
  - page-about
  - page-ecosystem
  - page-blog
  - page-events
  - page-basic-template-1
  - page-basic-template-2
  - page-get-involved
- type: directory
  path: content/data
  label: Data
  create: all
  match: "**/*"
  new_doc_ext: json
- type: directory
  path: content/blog
  label: Blog Posts
  create: all
  match: "**/*"
  new_doc_ext: json
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - NODE_ENV=production
  - SERVER_ENV=production
  preview_output_directory: dist
  install_dependencies_command: npm ci
  preview_docker_image: forestryio/node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run generate
