name: Auto approve

on:
  pull_request:
    branches:    
      - master

jobs:
  auto-approve:
    if: ${{ github.head_ref == 'manual-update'}}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: hmarr/auto-approve-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
