name: CI 

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - run: npm install
      - run: npm test
      - run: npm run build
      - uses: actions/upload-artifact@v2.2.0
        with:
          name: site
          path: _site
